// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Banner: typeof import('./src/components/common/Banner.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    Header: typeof import('./src/components/layout/header/Header.vue')['default']
    IconPark: typeof import('./src/components/common/IconPark.vue')['default']
    Menu: typeof import('./src/components/layout/menu/Menu.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Search: typeof import('./src/components/layout/header/Search.vue')['default']
    SearchList: typeof import('./src/components/layout/header/SearchList.vue')['default']
  }
}
